# Generated by Django 3.2.9 on 2021-11-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolkats_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='fields',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='motivations',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='web_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]