# Generated by Django 3.2.9 on 2021-11-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolkats_app', '0003_availabletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='endTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
