# Generated by Django 3.2.9 on 2021-11-14 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coolkats_app', '0005_auto_20211114_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
